INSERT INTO public.convidados_lista (responsavel, quantidade_maxima, origem, observacoes)
VALUES
('Pai', 2, 'noiva', NULL),
('Tia Giselia', 1, 'noiva', NULL),
('Dudinha', 3, 'noiva', '2 crianças'),
('Tio Negão', 3, 'noiva', NULL),
('Samuel', 2, 'noiva', '1 criança'),
('Tio Teteu', 4, 'noiva', NULL),
('Tia Ivanoscka', 3, 'noiva', NULL),
('Priscylla', 2, 'noiva', '1 criança'),
('Tio Degô', 2, 'noiva', NULL),
('Vanessa', 2, 'noiva', NULL),
('Tati', 2, 'noiva', NULL),
('Tia Suyanne', 2, 'noiva', NULL),
('Matheus', 2, 'noiva', '2 crianças'),
('Tio Gogói', 2, 'noiva', NULL),
('Tio Ronaldo', 3, 'noiva', NULL),
('Tio Douglas', 2, 'noiva', NULL),
('Isa', 5, 'noiva', '1 criança'),
('Abigail', 2, 'noiva', '1 criança'),
('Tio Samuel', 3, 'noiva', NULL),
('Pokémon', 2, 'noiva', NULL),
('Morgana', 2, 'noiva', NULL),
('Vitoria', 2, 'noiva', NULL),
('Leticia Manika', 2, 'noiva', NULL),
('Lhais', 2, 'noiva', NULL),
('Tia Ingrith', 2, 'noiva', NULL),
('Brenda/Bianca - EUA', 2, 'noiva', NULL),
('Sofia Batista', 1, 'noiva', NULL),
('Pedro Yuri - Faculdade', 1, 'noiva', NULL),
('Tio Paulo', 3, 'noiva', NULL),
('Taynara', 1, 'noiva', NULL),
('Tia Rose', 1, 'noiva', NULL),
('Tio Zé Pedro', 2, 'noiva', NULL),
('Tia Lane', 2, 'noiva', NULL),
('Tia Mazé', 2, 'noiva', NULL),
('Hygor', 1, 'noiva', NULL),
('Adrielle', 2, 'noiva', NULL),
('Tio Victor Granjo', 2, 'noiva', NULL),
('Tio Paulo Roberto', 5, 'noiva', NULL),
('Tio Edelson', 2, 'noiva', NULL),
('Tia Fátima', 2, 'noivo', NULL),
('Fábio', 2, 'noivo', NULL),
('Fabiana', 3, 'noivo', NULL),
('Levi', 2, 'noivo', NULL),
('Pai', 1, 'noivo', NULL),
('Tio Sérgio', 5, 'noivo', NULL),
('Mãe', 3, 'noivo', NULL),
('Avô Manoel Cordeiro', 4, 'noivo', NULL),
('Tio Juliano', 1, 'noivo', NULL),
('Tia Angela', 1, 'noivo', NULL),
('Tio Paulo', 3, 'noivo', NULL),
('Dennys', 1, 'noivo', NULL),
('Carlos', 2, 'noivo', NULL),
('André - Maceió', 2, 'noivo', NULL),
('Wilderson', 2, 'noivo', NULL),
('Jean', 2, 'amigos', '1 criança'),
('Mário Filho', 2, 'amigos', NULL),
('Pastor Josué', 2, 'amigos', '1 criança'),
('Dan', 2, 'amigos', '1 criança'),
('Dhoni', 3, 'amigos', '1 criança'),
('Guilherme maromba', 2, 'amigos', NULL),
('Mateus/Clara', 4, 'amigos', NULL),
('Mateus preto', 2, 'amigos', NULL),
('Renan', 1, 'amigos', NULL),
('Lucas', 1, 'amigos', NULL),
('Vitu Maia', 1, 'amigos', NULL),
('João Gui', 1, 'amigos', NULL),
('Gui Fabricío', 1, 'amigos', NULL),
('Thiago/Bea', 2, 'amigos', '1 criança'),
('Tio Messias', 3, 'amigos', NULL),
('Betinho/Iasmin', 2, 'amigos', '1 criança'),
('Senna', 2, 'amigos', '1 criança'),
('Ramon louvor', 2, 'amigos', NULL),
('Portela', 2, 'amigos', NULL),
('Pastor Luis Carlos', 2, 'amigos', NULL),
('Alê', 2, 'amigos', '2 crianças'),
('Pastor Willame', 2, 'amigos', NULL),
('Aure', 2, 'amigos', NULL),
('Maya', 1, 'amigos', NULL),
('Madson', 2, 'amigos', NULL),
('Italo Bruno', 2, 'amigos', '1 criança'),
('Hadna', 1, 'amigos', NULL);
